services:
  api-gateway:
    build:
      context: ./api-gateway
      target: dev
    volumes:
      - ./api-gateway/src:/app/src
    command: npm run dev
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
  user-service:
    build:
      context: ./services/user-service
      target: dev
    volumes:
      - ./services/user-service/src:/app/src
      - ./common:/app/common
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
  product-service:
    build:
      context: ./services/product-service
      target: dev
    volumes:
      - ./services/product-service/src:/app/src
      - ./common:/app/common
    command: npm run dev
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development

  category-service:
    build:
      context: ./services/category-service
      target: dev
    volumes:
      - ./services/category-service/src:/app/src
      - ./common:/app/common
    command: npm run dev
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: development

  notification-service:
    build:
      context: ./services/notification-service
      target: dev
    volumes:
      - ./services/notification-service/src:/app/src
      - ./common:/app/common
    command: npm run dev
    ports:
      - "3004:3004"
    environment:
      NODE_ENV: development

  inventory-service:
    build:
      context: ./services/inventory-service
      target: dev
    volumes:
      - ./services/inventory-service/src:/app/src
      - ./common:/app/common
    command: npm run dev
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: development

  cart-service:
    build:
      context: ./services/cart-service
      target: dev
    volumes:
      - ./services/cart-service/src:/app/src
      - ./common:/app/common
    command: npm run dev
    ports:
      - "3006:3006"
    environment:
      NODE_ENV: development
