services:
  user-service:
    build:
      context: ./services/user-service
      target: dev
    volumes:
      - ./services/user-service/src:/app/src
      - ./common:/app/common
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
  product-service:
    build:
      context: ./services/product-service
      target: dev
    volumes:
      - ./services/product-service/src:/app/src
      - ./common:/app/common
    command: npm run dev
    ports:
      - "3002:3002"
