version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - mynet

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - mynet

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # UI quản trị
    networks:
      - mynet

  user-service:
    build:
      context: ./services/user-service
      target: prod
    ports:
      - "3001:3001"
    env_file:
      - ./services/user-service/.env
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - mynet

  product-service:
    build:
      context: ./services/product-service
      target: prod
    ports:
      - "3002:3002"
    env_file:
      - ./services/product-service/.env
    depends_on:
      - mysql
      - redis
      - rabbitmq
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
